/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    Users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    Users: User;
    Media: Media;
    CourseItems: CourseItem;
    Programmes: Programme;
    Pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    Users: UsersSelect<false> | UsersSelect<true>;
    Media: MediaSelect<false> | MediaSelect<true>;
    CourseItems: CourseItemsSelect<false> | CourseItemsSelect<true>;
    Programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    Pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    HomeSettings: HomeSetting;
    SiteSettings: SiteSetting;
  };
  globalsSelect: {
    HomeSettings: HomeSettingsSelect<false> | HomeSettingsSelect<true>;
    SiteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'Users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CourseItems".
 */
export interface CourseItem {
  id: string;
  name: string;
  level: 'IGCSE' | 'IELTS' | 'Level 3' | 'Level 4' | 'Level 5' | 'Level 4 & 5' | 'Level 6' | 'Level 7';
  credits?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Programmes".
 */
export interface Programme {
  id: string;
  level: 'BA Pathway' | 'MBA Pathway';
  title: string;
  description: string;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: 'about' | 'services' | 'why-choose' | 'contact' | 'courses' | 'study';
  heroBadge?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  overviewTitle?: string | null;
  overviewParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  missionTitle?: string | null;
  missionBody?: string | null;
  visionTitle?: string | null;
  visionBody?: string | null;
  valuesSectionTitle?: string | null;
  valuesSectionSubtitle?: string | null;
  coreValues?:
    | {
        icon?:
          | (
              | 'award'
              | 'book-open'
              | 'clock'
              | 'credit-card'
              | 'eye'
              | 'file-text'
              | 'globe'
              | 'graduation-cap'
              | 'headphones'
              | 'heart'
              | 'lightbulb'
              | 'message-circle'
              | 'shield'
              | 'target'
              | 'trending-up'
              | 'user-check'
              | 'users'
            )
          | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  partnershipTitle?: string | null;
  partnershipBody?: string | null;
  partnershipButtonLabel?: string | null;
  partnershipButtonHref?: string | null;
  reasonsSectionTitle?: string | null;
  reasonsSectionSubtitle?: string | null;
  reasons?:
    | {
        icon?:
          | (
              | 'award'
              | 'book-open'
              | 'clock'
              | 'credit-card'
              | 'eye'
              | 'file-text'
              | 'globe'
              | 'graduation-cap'
              | 'headphones'
              | 'heart'
              | 'lightbulb'
              | 'message-circle'
              | 'shield'
              | 'target'
              | 'trending-up'
              | 'user-check'
              | 'users'
            )
          | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  expectationsTitle?: string | null;
  expectationsBody?: string | null;
  expectationPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  testimonialQuote?: string | null;
  testimonialAuthor?: string | null;
  testimonialRole?: string | null;
  commitmentTitle?: string | null;
  commitmentBody?: string | null;
  commitmentBadges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  serviceNoteText?: string | null;
  servicesSectionTitle?: string | null;
  servicesSectionSubtitle?: string | null;
  serviceCards?:
    | {
        icon?:
          | (
              | 'award'
              | 'book-open'
              | 'clock'
              | 'credit-card'
              | 'eye'
              | 'file-text'
              | 'globe'
              | 'graduation-cap'
              | 'headphones'
              | 'heart'
              | 'lightbulb'
              | 'message-circle'
              | 'shield'
              | 'target'
              | 'trending-up'
              | 'user-check'
              | 'users'
            )
          | null;
        title: string;
        description: string;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  processSectionTitle?: string | null;
  processSectionSubtitle?: string | null;
  processSteps?:
    | {
        step: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  formTitle?: string | null;
  formSubtitle?: string | null;
  contactInfoTitle?: string | null;
  contactInfoSubtitle?: string | null;
  whatsappTitle?: string | null;
  whatsappBody?: string | null;
  trustBannerText?: string | null;
  filterLabel?: string | null;
  levelDescriptions?:
    | {
        level: 'IGCSE' | 'IELTS' | 'Level 3' | 'Level 4' | 'Level 5' | 'Level 4 & 5' | 'Level 6' | 'Level 7';
        description: string;
        id?: string | null;
      }[]
    | null;
  disclaimerText?: string | null;
  noticeTitle?: string | null;
  noticeBody?: string | null;
  aboutTitle?: string | null;
  aboutParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  programmesSectionTitle?: string | null;
  programmesSectionSubtitle?: string | null;
  benefitsSectionTitle?: string | null;
  benefitsSectionSubtitle?: string | null;
  studyBenefits?:
    | {
        icon?:
          | (
              | 'award'
              | 'book-open'
              | 'clock'
              | 'credit-card'
              | 'eye'
              | 'file-text'
              | 'globe'
              | 'graduation-cap'
              | 'headphones'
              | 'heart'
              | 'lightbulb'
              | 'message-circle'
              | 'shield'
              | 'target'
              | 'trending-up'
              | 'user-check'
              | 'users'
            )
          | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  affordabilityTitle?: string | null;
  affordabilityBody?: string | null;
  ctaTitle?: string | null;
  ctaBody?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'Users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'Media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'CourseItems';
        value: string | CourseItem;
      } | null)
    | ({
        relationTo: 'Programmes';
        value: string | Programme;
      } | null)
    | ({
        relationTo: 'Pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'Users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'Users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CourseItems_select".
 */
export interface CourseItemsSelect<T extends boolean = true> {
  name?: T;
  level?: T;
  credits?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  level?: T;
  title?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroBadge?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  content?: T;
  overviewTitle?: T;
  overviewParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  missionTitle?: T;
  missionBody?: T;
  visionTitle?: T;
  visionBody?: T;
  valuesSectionTitle?: T;
  valuesSectionSubtitle?: T;
  coreValues?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  partnershipTitle?: T;
  partnershipBody?: T;
  partnershipButtonLabel?: T;
  partnershipButtonHref?: T;
  reasonsSectionTitle?: T;
  reasonsSectionSubtitle?: T;
  reasons?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  expectationsTitle?: T;
  expectationsBody?: T;
  expectationPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  testimonialQuote?: T;
  testimonialAuthor?: T;
  testimonialRole?: T;
  commitmentTitle?: T;
  commitmentBody?: T;
  commitmentBadges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  serviceNoteText?: T;
  servicesSectionTitle?: T;
  servicesSectionSubtitle?: T;
  serviceCards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  processSectionTitle?: T;
  processSectionSubtitle?: T;
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  formTitle?: T;
  formSubtitle?: T;
  contactInfoTitle?: T;
  contactInfoSubtitle?: T;
  whatsappTitle?: T;
  whatsappBody?: T;
  trustBannerText?: T;
  filterLabel?: T;
  levelDescriptions?:
    | T
    | {
        level?: T;
        description?: T;
        id?: T;
      };
  disclaimerText?: T;
  noticeTitle?: T;
  noticeBody?: T;
  aboutTitle?: T;
  aboutParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  programmesSectionTitle?: T;
  programmesSectionSubtitle?: T;
  benefitsSectionTitle?: T;
  benefitsSectionSubtitle?: T;
  studyBenefits?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  affordabilityTitle?: T;
  affordabilityBody?: T;
  ctaTitle?: T;
  ctaBody?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeSettings".
 */
export interface HomeSetting {
  id: string;
  heroTitle: string;
  heroSubtitle: string;
  heroImage?: (string | null) | Media;
  trustIndicators?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        sublabel?: string | null;
        id?: string | null;
      }[]
    | null;
  featuresSectionTitle?: string | null;
  featuresSectionSubtitle?: string | null;
  features?:
    | {
        icon?:
          | (
              | 'award'
              | 'book-open'
              | 'clock'
              | 'credit-card'
              | 'eye'
              | 'file-text'
              | 'globe'
              | 'graduation-cap'
              | 'headphones'
              | 'heart'
              | 'lightbulb'
              | 'message-circle'
              | 'shield'
              | 'target'
              | 'trending-up'
              | 'user-check'
              | 'users'
            )
          | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  partnershipTitle?: string | null;
  partnershipBody?: string | null;
  partnershipBadges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaBody?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettings".
 */
export interface SiteSetting {
  id: string;
  siteTitle?: string | null;
  siteShortName?: string | null;
  siteSuffix?: string | null;
  headerPartnerLabel?: string | null;
  headerCtaLabel?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  whatsappNumber?: string | null;
  address?: string | null;
  officeHours?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  footerDescription?: string | null;
  footerPartnerLabel?: string | null;
  footerDisclaimer?: string | null;
  headerNavigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerQuickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerResourceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerExternalLabel?: string | null;
  footerExternalHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeSettings_select".
 */
export interface HomeSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  trustIndicators?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        sublabel?: T;
        id?: T;
      };
  featuresSectionTitle?: T;
  featuresSectionSubtitle?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  partnershipTitle?: T;
  partnershipBody?: T;
  partnershipBadges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaBody?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteShortName?: T;
  siteSuffix?: T;
  headerPartnerLabel?: T;
  headerCtaLabel?: T;
  contactEmail?: T;
  contactPhone?: T;
  whatsappNumber?: T;
  address?: T;
  officeHours?:
    | T
    | {
        text?: T;
        id?: T;
      };
  footerDescription?: T;
  footerPartnerLabel?: T;
  footerDisclaimer?: T;
  headerNavigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerQuickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerResourceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerExternalLabel?: T;
  footerExternalHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}